//! Raw FFI bindings to the Intel oneMKL 2026.1.0 C interface.
//!
//! These bindings are generated by `bindgen` from the oneMKL headers acquired
//! by [`nuvai_mkl_src`]. They are low-level and `unsafe`; prefer the safe
//! [`nuvai_mkl`] wrapper for day-to-day use.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(clippy::all)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]
#![allow(deref_nullptr)]
// bindgen pulls malloc/realloc prototypes from transitively-included stdlib
// headers; they are never used, but the "suspicious runtime symbol" lint fires.
#![allow(suspicious_runtime_symbol_definitions)]

pub use nuvai_mkl_src::MKL_VERSION;

// Re-export the link/location metadata for downstream introspection.
pub use nuvai_mkl_src::MklInfo;

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
