//! Raw FFI bindings to the Intel oneMKL 2026.1.0 C interface.
//!
//! These bindings are generated by `bindgen` from the oneMKL headers acquired
//! by [`nuvai_mkl_src`] on Intel targets. On Apple Silicon
//! (`aarch64-apple-darwin`), where Intel ships no oneMKL, the crate compiles a
//! hand-written FFI surface against the Accelerate framework instead. Either
//! way the bindings are low-level and `unsafe`; prefer the safe [`nuvai_mkl`]
//! wrapper for day-to-day use.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(clippy::all)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]
#![allow(deref_nullptr)]
// bindgen pulls malloc/realloc prototypes from transitively-included stdlib
// headers (and the aarch64 module declares `malloc`/`free` to back the default
// sparse options); they are never called directly, but the "suspicious runtime
// symbol" lint fires.
#![allow(suspicious_runtime_symbol_definitions)]

pub use nuvai_mkl_src::MKL_VERSION;

// Re-export the link/location metadata for downstream introspection.
pub use nuvai_mkl_src::MklInfo;

#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
mod aarch64;
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
pub use aarch64::*;

#[cfg(not(target_os = "macos"))]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
